name: skybase
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  get: ^4.6.5
  dio: ^4.0.6

  # Database
  get_storage: ^2.0.3
  flutter_secure_storage: ^7.0.1
  hive: ^2.2.3

  # Notifications
  flutter_local_notifications: ^13.0.0

  # File Manager
  flutter_downloader: ^1.9.1
  android_path_provider: ^0.3.0
  image: ^3.2.0
  camera: ^0.10.1
  photo_manager: ^2.5.2
  cached_network_image: ^3.2.3
  path: ^1.8.2

  # Widget
  modal_bottom_sheet: ^2.1.2
  infinite_scroll_pagination: ^3.2.0
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.5
  lottie: ^2.2.0
  flutter_svg: ^1.1.6
  percent_indicator: ^4.2.2

  # Others
  package_info_plus: ^3.0.2
  permission_handler: ^10.2.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  double_back_to_close_app: ^2.1.0
  rename: ^2.1.1
  device_preview: ^1.1.0
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.0.12
  firebase_remote_config: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/anim/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true