name: skybase
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  get: ^4.6.5
  dio: ^5.2.1+1

  # Database
  get_storage: ^2.1.1
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3

  # File Manager
  flutter_downloader: ^1.9.1
  android_path_provider: ^0.3.0
  image: ^4.0.17
  camera: ^0.10.5+2
  photo_manager: ^2.6.0
  image_picker: ^0.8.9
  file_picker: ^5.3.2
  flutter_image_compress: ^2.0.3
  chewie: ^1.5.0
  video_player: ^2.6.1
  cached_network_image: ^3.2.3
  path: ^1.8.3

  # Widget
  flutter_rating_bar: ^4.0.0
  modal_bottom_sheet: ^3.0.0-pre
  infinite_scroll_pagination: ^4.0.0-dev.1
  shimmer: ^3.0.0
  calendar_date_picker2: ^0.5.2
  cupertino_icons: ^1.0.5
  lottie: ^2.4.0
  flutter_svg: ^2.0.7
  introduction_screen: ^3.1.4
  dotted_border: ^2.0.0+3
  percent_indicator: ^4.2.2
  carousel_slider: ^4.2.1

  # Others
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  permission_handler: ^10.3.0
  intl: ^0.18.0
  path_provider: ^2.0.15
  double_back_to_close_app: ^2.1.0
  internet_file: ^1.2.0
  open_filex: ^4.3.2
  mask_text_input_formatter: ^2.4.0
  device_preview: ^1.1.0
  equatable: ^2.0.5
  device_info_plus: ^9.0.2

  # Firebase
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.0.12
  firebase_remote_config: ^3.0.10
  store_redirect: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  rename: ^2.1.1
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.8

dependency_overrides:
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/anim/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true